### PR TITLE
Add unfinished ru_RU.lang

### PR DESCRIPTION
**Pull request by kraineff**

### CODE REVIEW

**Comment by makeo** [comment]
Thanks! :) There is still new stuff coming so you maybe have to update the file again.
I will accept your pull as soon as a new version is released

**Comment by kraineff** [comment]
You can merge it. I can will make new pull request. Like translate other mod

**Comment by kraineff** [comment]
And 1  question. Gadomancy is like Golemancy but Gado. Yes?

**Comment by makeo** [comment]
ok i will merge it :D
I created Gadomancy using "Gad(get)". The "mancy" is created using (Gole)mancy and the "o" is there because otherwise it would be difficult to pronounce

**Pull request merged**
