### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
Yet another language file. 
~~Please do not merge this pull request temporarily. I believe that I can finish it _tomorrow_.~~
Finished! Cheer!

### CODE REVIEW

**Comment by HellFirePvP** [comment]
Awesome ;)

Just comment here when you're done.

**Comment by 3TUSK** [comment]
Okay, it is good to go. Thanks for your patience :)

**Comment by HellFirePvP** [comment]
Awesome! However, we cannot merge it into the master branch, because that messes up some stuff.

We'll merge it manually on our local projects and push it later. It will be available in the next version! ;)

**Comment by 3TUSK** [comment]
OK no problem

**Comment by HellFirePvP** [comment]
File has been added and will be included for the next update. However, we don't have the texts for the next update yet, if you want to translate the entries before we release the update, please let me know.

**Comment by 3TUSK** [comment]
Well I am willing to help on translation, but my IRL things make me busy...

**Comment by HellFirePvP** [comment]
We don't need to rush it. We still don't have the texts ourselves

**Comment by 3TUSK** [comment]
Okay. Once I have time I will come back to help on translation. 
How about closing this pr right now?

**Comment by HellFirePvP** [comment]
Well, you deleted the repository that was connected to this PR, but i guess i'm just gonna write here again. We finished the texts for the next update.

However, we'll update tomorrow (most likely), so if you can't finish it in time don't worry, because 1.0.7 will also come soon.

Quicklink to the new language file for 1.0.6: https://github.com/makeoo/Gadomancy/blob/dev/src/main/resources/assets/gadomancy/lang/en_US.lang

**Comment by 3TUSK** [comment]
Ah, thanks for reminder. I will take a look at new language file as long as I get some free time.

**Pull request closed without merging**
