### PR TITLE
Thaumonomicon Entries and Edits!

### PR DESCRIPTION
**Pull request by BBoldt**
-- Added new entries for items that haven't gotten them yet
-- Changed some of the "research texts" to be references to things I thought would be funnier. :P
-- Edited all the text involving node growth to be easier to understand, and fixed some grammar mistakes. Tried to stay as close to the original as possible, but I did change quite a bit.
-- Infusion Claw will need an extra page. I added it to the lang file as: "gadomancy.research_page.INFUSIONCLAW.2"

Anyways, hope this helps! If you need any others in the future, make an issue on this github and ping me. @BBoldt

### CODE REVIEW

**Comment by makeo** [comment]
Sounds great! I'll take a look at it in a few hours :)

**Comment by HellFirePvP** [comment]
tc.research_text.GADOMANCY.GROWING=Feed me Semour

awesome :'D - I don't have the time now but i'll take a closer look later today~

**Comment by makeo** [comment]
Wow your "research texts" are amazing! little shop of horrors :D

**Comment by HellFirePvP** [comment]
So, we decided what we'll take, but i fear we cannot merge the PR, because it'll fuck up some data structures... I'll merge your texts manually.

If you're up to writing new entries, here ([**SPOILER ALERT**] https://github.com/makeoo/Gadomancy/issues/21 ) you go ;) :sparkles:

#Edit: _ping ping_ @BBoldt :grin:

**Pull request closed without merging**
